fix: add is-url as dependency to quicktype-core
quicktype-core has a direct dependency on is-url, however this is not listed as such.

```
Error: Cannot find module 'is-url'
Require stack:
- /Users/alanagius/git/angular-cli/node_modules/quicktype-core/dist/input/io/NodeIO.js
- /Users/alanagius/git/angular-cli/node_modules/quicktype-core/dist/index.js
- /Users/alanagius/git/angular-cli/tools/quicktype_runner.js
- /Users/alanagius/git/angular-cli/scripts/build-schema.ts
- /Users/alanagius/git/angular-cli/scripts/build.ts
- /Users/alanagius/git/angular-cli/bin/devkit-admin
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (/Users/alanagius/git/angular-cli/lib/bootstrap-local.js:133:29)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/alanagius/git/angular-cli/node_modules/quicktype-core/dist/input/io/NodeIO.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
```